### ISSUE TITLE
What would be the best action to make it interactive

### ISSUE THREAD

**Issue by premonday** [rohitkvv/vue-simple-complete#37]
Hi, I just got the component working and its the perfect solution for me + its behaviour, what would be the best way to add an Enter or button action to execute the search using the objectMatchkey?

Thanks

**Comment by rohitkvv** [comment]
@premonday  Good to hear that this was useful to you 😃 Currently, it does support "Enter" button for selection, but you would have to first highlight the item using the up/down keys and then press Enter to select it. Is that what you are asking about?

Or, is it that when there is only 1 match, you want to select it immediately by pressing Enter key, rather than using arrow keys first to highlight the item and then press Enter to select it?

**Comment by rohitkvv** [comment]
@premonday closing this issue for now, message me if you have any further queries.
